jobs:
  - job: Windows
    pool:
      name: Hosted VS2017
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.x
      - script: 'yarn install'
        displayName: 'Install dependencies'
      - script: 'yarn lint'
        displayName: 'Run linter'
      - script: 'yarn test'
        displayName: 'Run tests'
      - script: 'node src/cli.js "yarn eslint src"'
        displayName: 'Test CLI'
  - job: macOS
    pool:
      name: Hosted macOS
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.x
      - script: 'yarn install'
        displayName: 'Install dependencies'
      - script: 'yarn lint'
        displayName: 'Run linter'
      - script: 'yarn test'
        displayName: 'Run tests'
      - script: 'node src/cli.js "yarn eslint src"'
        displayName: 'Test CLI'
  - job: Linux
    pool:
      name: Hosted Ubuntu 1604
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.x
      - script: 'yarn install'
        displayName: 'Install dependencies'
      - script: 'yarn lint'
        displayName: 'Run linter'
      - script: 'yarn test'
        displayName: 'Run tests'
      - script: 'node src/cli.js "yarn eslint src"'
        displayName: 'Test CLI'
